In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../krishnlp/data/train.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [5]:
df=df.dropna()

In [6]:
df.shape

(18285, 5)

In [7]:
X=df.drop('label',axis=1)

In [8]:
y=df['label']

In [9]:
X.shape

(18285, 4)

In [10]:
y.shape

(18285,)

In [11]:
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [12]:
import tensorflow as tf

In [13]:
tf.__version__

'2.10.1'

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [15]:
### Vocabulary size
voc_size=5000

In [16]:
messages=X.copy()

In [17]:
messages.head(1)

id                                              title         author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...  Darrell Lucus   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...

In [18]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [19]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [20]:
messages.reset_index(inplace=True)

In [21]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [22]:
import nltk
import re
from nltk.corpus import stopwords
# https://colab.research.google.com/drive/1CoNxaecjcsAKwDEwNpBmvsKjVFpNTdv0?usp=sharing#scrollTo=WOYLZSrdkQbB

In [23]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sopan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [24]:
## Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [25]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [26]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [27]:
onehot_repr=[one_hot(words,voc_size) for words in  corpus]
onehot_repr

[[386, 720, 2111, 3114, 3354, 1168, 3336, 740, 4563, 3408],
 [1180, 3957, 556, 2320, 3928, 4610, 4192],
 [4778, 3671, 1255, 4300],
 [4814, 280, 2452, 294, 1950, 528],
 [4027, 3928, 1187, 4997, 2528, 1373, 3928, 1512, 4913, 1645],
 [3134,
  17,
  4640,
  1827,
  2407,
  312,
  3374,
  449,
  3041,
  1444,
  3733,
  1162,
  4283,
  4093,
  4192],
 [1043, 518, 2946, 4646, 2928, 4364, 4016, 2684, 4203, 4607, 253],
 [4480, 297, 1808, 4907, 3016, 52, 312, 314, 4203, 4607, 253],
 [2556, 4981, 2298, 4649, 946, 430, 4222, 4737, 312, 1728],
 [1720, 1422, 4651, 3788, 379, 366, 3581, 2039],
 [4697, 4059, 3548, 3213, 1509, 4196, 4173, 4045, 1073, 4898, 135],
 [294, 2888, 3354, 430, 312, 3016],
 [1925, 1111, 3069, 4359, 4410, 2272, 2388, 3062, 2465],
 [941, 1265, 3695, 3395, 4342, 466, 3050, 4203, 4607, 253],
 [454, 2186, 2836, 11, 1316, 4203, 4607, 253],
 [3087, 1349, 1763, 3218, 941, 1698, 4654, 4359, 2245, 1261],
 [3217, 2985, 3957],
 [733, 695, 3136, 3210, 312, 4569, 2064, 4192],
 [4143, 4912, 5

In [28]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [29]:
onehot_repr[1]

[1180, 3957, 556, 2320, 3928, 4610, 4192]

In [30]:
sent_length=20
embaded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embaded_docs)

[[ 386  720 2111 ...    0    0    0]
 [1180 3957  556 ...    0    0    0]
 [4778 3671 1255 ...    0    0    0]
 ...
 [1343  447 1017 ...    0    0    0]
 [4186 3016 2725 ...    0    0    0]
 [2337 1252 2862 ...    0    0    0]]


In [34]:
embaded_docs

array([[ 386,  720, 2111, ...,    0,    0,    0],
       [1180, 3957,  556, ...,    0,    0,    0],
       [4778, 3671, 1255, ...,    0,    0,    0],
       ...,
       [1343,  447, 1017, ...,    0,    0,    0],
       [4186, 3016, 2725, ...,    0,    0,    0],
       [2337, 1252, 2862, ...,    0,    0,    0]])

In [31]:
embaded_docs[1]

array([1180, 3957,  556, 2320, 3928, 4610, 4192,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [33]:
onehot_repr[1]

[1180, 3957, 556, 2320, 3928, 4610, 4192]

In [32]:
embaded_docs[0]

array([ 386,  720, 2111, 3114, 3354, 1168, 3336,  740, 4563, 3408,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [36]:
#creating model
model=Sequential() ##name of the model
embedding_vector_feature=40 ##feature presentation[........40 feature for each word]
model.add(Embedding(voc_size,embedding_vector_feature,input_length=sent_length)) ##creting embedding layer
model.add(LSTM(100)) ### LSTM neural network
model.add(Dense(1,activation='sigmoid'))  ## due to output layer is binary e need to add sigmid function
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy']) #feature of model 
print(model.summary()) ## model summary

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [38]:
len(embaded_docs),y.shape

(18285, (18285,))

In [39]:
import numpy as np
X_final=np.array(embaded_docs)
y_final=np.array(y)

In [41]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [42]:
X_final,y_final

(array([[ 386,  720, 2111, ...,    0,    0,    0],
        [1180, 3957,  556, ...,    0,    0,    0],
        [4778, 3671, 1255, ...,    0,    0,    0],
        ...,
        [1343,  447, 1017, ...,    0,    0,    0],
        [4186, 3016, 2725, ...,    0,    0,    0],
        [2337, 1252, 2862, ...,    0,    0,    0]]),
 array([1, 0, 1, ..., 0, 1, 1], dtype=int64))

In [47]:
from sklearn.model_selection import train_test_split 
X_train,X_test, y_train, y_test=train_test_split(X_final,y_final,test_size=0.33, random_state=0)

In [48]:
##finally training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10, batch_size=64)

Epoch 1/10
192/192 [==============================] - 12s 44ms/step - loss: 0.3071 - accuracy: 0.8522 - val_loss: 0.2022 - val_accuracy: 0.9163
Epoch 2/10
192/192 [==============================] - 7s 38ms/step - loss: 0.1336 - accuracy: 0.9498 - val_loss: 0.2209 - val_accuracy: 0.9138
Epoch 3/10
192/192 [==============================] - 9s 45ms/step - loss: 0.0914 - accuracy: 0.9691 - val_loss: 0.2487 - val_accuracy: 0.9152
Epoch 4/10
192/192 [==============================] - 9s 45ms/step - loss: 0.0602 - accuracy: 0.9793 - val_loss: 0.2499 - val_accuracy: 0.9210
Epoch 5/10
192/192 [==============================] - 7s 39ms/step - loss: 0.0470 - accuracy: 0.9857 - val_loss: 0.2956 - val_accuracy: 0.9128
Epoch 6/10
192/192 [==============================] - 8s 41ms/step - loss: 0.0371 - accuracy: 0.9877 - val_loss: 0.3807 - val_accuracy: 0.9069
Epoch 7/10
192/192 [==============================] - 7s 38ms/step - loss: 0.0263 - accuracy: 0.9922 - val_loss: 0.3890 - val_accuracy: 0.907

In [49]:
y_pred=model.predict(X_test)

189/189 [==============================] - 3s 10ms/step


In [50]:
y_pred=np.where(y_pred>0.5,1,0) ##AUC RDC Curve

In [54]:
from sklearn.metrics import confusion_matrix

In [57]:
confusion_matrix(y_test,y_pred)

array([[3119,  270],
       [ 295, 2351]], dtype=int64)

In [58]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9063794531897266

In [59]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.92      0.92      3389
           1       0.90      0.89      0.89      2646

    accuracy                           0.91      6035
   macro avg       0.91      0.90      0.90      6035
weighted avg       0.91      0.91      0.91      6035



In [ ]:
# https://colab.research.google.com/drive/1CoNxaecjcsAKwDEwNpBmvsKjVFpNTdv0?usp=sharing#scrollTo=7XvLoCHBkQbH
# https://www.youtube.com/watch?v=k3_qIfRogyY&list=PLZoTAELRMXVNNrHSKv36Lr3_156yCo6Nn&index=12
# https://colab.research.google.com/drive/1CoNxaecjcsAKwDEwNpBmvsKjVFpNTdv0?usp=sharing#scrollTo=7XvLoCHBkQbH

# youtube https://www.youtube.com/watch?v=gFwr2KxZ1pc&list=PLZoTAELRMXVNNrHSKv36Lr3_156yCo6Nn&index=13